export const academicBuildings = [
	"academic activities building",
	"agricultural sciences and industries building",
	"armsby building",
	"biobehavioral health building",
	"boucke",
	"boucke building",
	"bryce jordan center",
	"business building",
	"chambers building",
	"chemical and biomedical engineering building",
	"chemistry building",
	"computer building",
	"davey lab",
	"deike building",
	"earth and engineering sciences building",
	"eisenhower auditorium",
	"eisenhower chapel",
	"ford building",
	"forest resources building",
	"forum building",
	"grange building",
	"hammond building",
	"henning building",
	"hhd building",
	"hosler building",
	"hub",
	"huck life sciences building",
	"im building",
	"innovation hub",
	"intramural building",
	"keller building",
	"leonhard building",
	"life sciences building",
	"mateer building",
	"mcallister building",
	"moore building",
	"music building i",
	"music building ii",
	"nursing sciences building",
	"osmond laboratory",
	"outreach building",
	"pasquerilla spiritual center",
	"reber building",
	"robeson center",
	"sackett building",
	"schwab auditorium",
	"shields building",
	"sparks",
	"sparks building",
	"stuckeman family building",
	"thomas building",
	"visual arts building",
	"wagner building",
	"wartik lab",
	"walker building",
	"west pattee library",
	"westgate building",
	"white building",
	"willard building",
];
