	export const academicBuildings = [
		"hub",
		"robeson center",
		"pasquerilla spiritual center",
		"eisenhower chapel",
		"schwab auditorium",
		"eisenhower auditorium",
		"bryce jordan center",
		"im building",
		"white building",
		"west pattee library",
		"sparks building",
		"boucke building",
		"business building",
		"keller building",
		"hammond building",
		"willard building",
		"thomas building",
		"westgate building",
		"walker building",
		"agricultural sciences and industries building",
		"forest resources building",
		"life sciences building",
		"huck life sciences building",
		"osmond laboratory",
		"deike building",
		"stuckeman family building",
		"visual arts building",
		"forum building",
		"hhd building",
		"davey lab",
		"sackett building",
		"earth and engineering sciences building",
		"mateer building",
		"chambers building",
		"moore building",
		"ford building",
		"henning building",
		"leonhard building",
		"reber building",
		"nursing sciences building",
		"chemical and biomedical engineering building",
		"chemistry building",
		"hosler building",
		"innovation hub",
		"grange building",
		"armsby building",
		"biobehavioral health building",
		"intramural building",
		"shields building",
		"wagner building",
		"wartik lab",
		"academic activities building",
		"outreach building",
		"mcallister building",
		"computer building",
		"music building i",
		"music building ii",
		"sparks",
		"boucke",
	];