export const PRESET_SKILLS = [
	"Bootstrap",
	"C#",
	"C++",
	"CSS",
	"Data Structures & Algorithms",
	"Django",
	"Express.js",
	"Firebase",
	"Flask",
	"Frontend",
	"Full Stack Development",
	"Git / Version Control",
	"HTML",
	"Java",
	"JavaScript",
	"Mock Interviews",
	"Mobile Development",
	"MongoDB",
	"MySQL",
	"Next.js",
	"Node.js",
	"Object-Oriented Programming",
	"PostgreSQL",
	"Python",
	"React",
	"REST APIs",
	"Resume Building",
	"SQL",
	"Supabase",
	"System Design",
	"Tailwind CSS",
	"UI/UX Design",
	"Web Development",
	"Backend Development",
];

export const PRESET_INTERESTS = ["Anime & Gaming", "Consulting", "Content Creation", "Cybersecurity", "Data Science & Analytics", "Diversity in Tech", "Leadership & Public Speaking", "Music & Performing Arts", "Product Management", "Program Management", "Project Management", "Software Engineering", "Sports & Fitness", "Startups & Entrepreneurship", "Stocks & Investing"];
